feat(HIVE-42): support forumpromo and eventpromo's from different brands
Financial-Times/n-magnet pull request #52
Opened 2021-03-18 16:25 UTC by maxcbc

# feat(HIVE-42): support forumpromo and eventpromo's from different brands

## What
- adds support for eventpromos from different brands (i.e. passes the 'brand' prop to the component)
- adds support for rendering 'forumpromo' if the api returns one
- updates demo with examples of the different brands and the 'forumpromo'

2021-04-13 10:16 UTC, mymoon1020 approved these changes

2021-04-22 14:14 UTC, AliceArmstrong requested changes
Nice work 🙌 One tiny formatting request, but otherwise looks good to go.

2021-04-23 09:28 UTC, maxcbc commented on src/components/forumpromo/main.js
> +
Fixed 🙂

2021-04-23 09:47 UTC, AliceArmstrong approved these changes
🌟

2021-04-26 08:02 UTC, maxcbc commented
@AliceArmstrong Thanks for the review & approve. Please can you merge it for me. I do not have the permissions to do so.

2021-04-27 08:20 UTC, merged