Add segmentId to external links
Financial-Times/n-magnet pull request #63
Opened 2021-08-09 11:37 UTC by ahmadmoawad

2021-08-10 08:49 UTC, maxcbc requested changes
We'll also need to do the same for forumPromos: https://github.com/Financial-Times/n-magnet/blob/main/src/components/forumpromo/main.js

2021-08-12 12:26 UTC, maxcbc requested changes

2021-08-12 12:26 UTC, maxcbc commented on src/components/forumpromo/main.js
> +		const promoElement = <Forumpromo {...formattedData} />;
i don't think that the data for a forumpromo is the same shape as that of an eventpromo, so I don't think using the same `getMappedData()` function will work.

A forumpromo's data has this format: https://github.com/Financial-Times/n-magnet/blob/main/demos/fixtures/promos/forumpromo.json
Whereas an eventpromo's data looks like this: https://github.com/Financial-Times/n-magnet/blob/main/demos/fixtures/promos/eventpromo/ft-live.json

2021-08-12 12:26 UTC, maxcbc commented on src/components/forumpromo/main.js
> +		const promoElement = <Forumpromo {...formattedData} />;
Have you managed to get the demo running? It might help you understand what data gets used where.

2021-08-12 12:31 UTC, ahmadmoawad commented on src/components/forumpromo/main.js
> +		const promoElement = <Forumpromo {...formattedData} />;
@maxcbc Yes, I have run the demo. It's not clear not to update which part in the https://github.com/Financial-Times/n-magnet/blob/main/src/components/forumpromo/main.js from the previous comment.

2021-08-13 08:13 UTC, maxcbc requested changes

2021-08-13 08:13 UTC, maxcbc commented on src/components/forumpromo/main.js
> +		forumUrl.searchParams.set('segmentId', segmentId);
I think you forgot to set `data.link` to the new url with `data.link = forumUrl.href`

2021-08-13 08:13 UTC, maxcbc commented on src/components/forumpromo/main.js
> +		forumUrl.searchParams.set('segmentId', segmentId);
Other than that this looks god

2021-08-13 08:17 UTC, maxcbc approved these changes

2021-08-13 11:21 UTC, AliceArmstrong approved these changes
👍

2021-08-13 13:27 UTC, merged